### ISSUE TITLE
Encourage feedback and say the app is in "beta"

### ISSUE THREAD

**Issue by jeanwalshie** [sfbrigade/adopt-a-drain#150] opened 2016-02-06 00:16 UTC
I'd like to state somewhere that the app is a work in progress and that we want user feedback. I think it might make sense to put this where it currently says "send feedback." We could change to something more peppy, like, "We want your feedback!" and add something about the app being in in beta testing phase (if that's actually what it's called) :)

**Comment by jszwedko** [comment] 2016-02-06 04:12
Closing this as a duplicate of #111, but definitely agree!

**Closed by jszwedko** 2016-02-06 04:12 UTC
Labels: copy
